IAC on AWS

diff --git a/.github/workflows/cd.yml b/.github/workflows/cd.yml
--- a/.github/workflows/cd.yml
+++ b/.github/workflows/cd.yml
@@ -12,22 +12,45 @@ jobs:
     if: ${{ github.event.workflow_run.conclusion == 'success' && vars.DEPLOY_ENABLED == 'true' }}
     runs-on: ubuntu-latest
     steps:
-      - uses: appleboy/ssh-action@v1
-        with:
-          host: ${{ secrets.EC2_HOST }}
-          username: ${{ secrets.EC2_USER }}
-          key: ${{ secrets.EC2_SSH_KEY }}
-          script: |
-            if [ ! -d ~/github-actions-kubernetes-masterclass ]; then
-              git clone ${{ github.server_url }}/${{ github.repository }}.git ~/github-actions-kubernetes-masterclass
-            fi
-            cd ~/github-actions-kubernetes-masterclass
-            git pull origin main
-            if [ ! -f .env ]; then
-              echo "ERROR: ~/github-actions-kubernetes-masterclass/.env is missing. Create it once with DOCKERHUB_USERNAME and DB credentials."
-              exit 1
-            fi
-            docker-compose pull
-            docker-compose up -d
-            docker image prune -f
+     - name: Checkout
+       uses: actions/checkout@v4 
+     - name: Configure AWS 
+       uses: aws-actions/configure-aws-credentials@v4 
+       with: 
+          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }} 
+          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 
+          aws-region: ${{ vars.AWS_REGION }} 
+     - name: Setup kubectl 
+       uses: azure/setup-kubectl@v4 
+     
+     - name: Update kubeconfig 
+       run: | 
+           aws eks update-kubeconfig --region ${{ vars.AWS_REGION }} --name dev-skillpulse-eks 
+     
+     - name: Deploy to EKS 
+       run: | 
+           kubectl apply -f k8s/
+
+
+
+
+# Deploy on EC2 instance with kind cluster already set.
+      # - uses: appleboy/ssh-action@v1
+      #   with:
+      #     host: ${{ secrets.EC2_HOST }}
+      #     username: ${{ secrets.EC2_USER }}
+      #     key: ${{ secrets.EC2_SSH_KEY }}
+      #     script: |
+      #       if [ ! -d ~/github-actions-kubernetes-masterclass ]; then
+      #         git clone ${{ github.server_url }}/${{ github.repository }}.git ~/github-actions-kubernetes-masterclass
+      #       fi
+      #       cd ~/github-actions-kubernetes-masterclass
+      #       git pull origin main
+      #       if [ ! -f .env ]; then
+      #         echo "ERROR: ~/github-actions-kubernetes-masterclass/.env is missing. Create it once with DOCKERHUB_USERNAME and DB credentials."
+      #         exit 1
+      #       fi
+      #       docker-compose pull
+      #       docker-compose up -d
+      #       docker image prune -f
 
